# Generated by Django 3.0.4 on 2020-03-17 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 23, 8, 53, 37961)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('SE', 'secondary'), ('W', 'warning'), ('S', 'success'), ('I', 'info'), ('D', 'dark'), ('L', 'light'), ('DA', 'danger')], default='P', max_length=2),
            preserve_default=False,
        ),
    ]
