# Generated by Django 3.0.4 on 2020-03-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200316_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
